name: Weekly Contributor Leaderboard

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight UTC
  workflow_dispatch:  # Also allows manual triggering from GitHub UI

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Contribution Stats
        uses: jpastorm/gh-contribution-stats@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: leaderboard.md
          since: 'last-week'  # You can also use '30 days' or 'last-month'

      - name: Commit and push leaderboard
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add leaderboard.md
          git commit -m "🔁 Weekly leaderboard update"
          git push
