name: Weekly Contributor Leaderboard

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch contributor stats and update leaderboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get a list of contributors and their commits
          echo "Fetching contributor stats..."
          
          # Set date range for the past week (change if necessary)
          since_date=$(date -d 'last Monday' --utc +%Y-%m-%dT%H:%M:%SZ)
          until_date=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          
          # Initialize leaderboard markdown file
          echo "# Weekly Contributor Leaderboard" > leaderboard.md
          echo "" >> leaderboard.md
          echo "| Contributor | Commits | Issues | Pull Requests | Reviews | Badge |" >> leaderboard.md
          echo "|-------------|---------|----------------|--------|---------|-------|" >> leaderboard.md
          
          # Fetch commits for the past week
          contributors_commits=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits?since=$since_date&until=$until_date")

          # Fetch issues created for the past week
          contributors_issues=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=all&since=$since_date&until=$until_date")

          # Extract commit data
          echo "$contributors_commits" | jq -r '.[] | "\(.author.login) | 1"' | \
            awk -F '|' '{ a[$1]+=$2 } END { for (i in a) print i, a[i] }' | \
            sort -k2 -nr | \
            while read contributor commits; do
              # Initialize badge
              badge="No Badge"
              
              # Assign badges based on commit contributions
              if [ "$commits" -gt 10 ]; then
                badge="Top Contributor"
              elif [ "$commits" -gt 5 ]; then
                badge="Rising Star"
              elif [ "$commits" -gt 2 ]; then
                badge="Consistent Contributor"
              fi
              
              # Write contributor and badge info to leaderboard
              echo "| @$contributor | $commits | 0 | 0 | 0 | $badge |" >> leaderboard.md
            done

          # Extract issues data
          echo "$contributors_issues" | jq -r '.[] | "\(.user.login) | 1"' | \
            awk -F '|' '{ a[$1]+=$2 } END { for (i in a) print i, a[i] }' | \
            sort -k2 -nr | \
            while read contributor issues; do
              # Initialize badge for issues
              badge="No Badge"
              
              # Assign badges based on issues created
              if [ "$issues" -gt 5 ]; then
                badge="Issue Master"
              elif [ "$issues" -gt 2 ]; then
                badge="Active Issue Creator"
              fi
              
              # Update leaderboard with issues data
              # We need to check if the contributor already exists from commits
              if grep -q "| @$contributor |" leaderboard.md; then
                sed -i "/| @$contributor |/s/0 | 0 | 0 |/$issues | 0 | $badge |/" leaderboard.md
              else
                echo "| @$contributor | 0 | 0 | $issues | 0 | $badge |" >> leaderboard.md
              fi
            done

          # Commit and push changes if there are updates
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git diff --exit-code leaderboard.md || (git add leaderboard.md && git commit -m "🔁 Weekly leaderboard update with badges" && git push)